import Head from 'next/head'
import styled from 'styled-components';
import { Inter } from '@next/font/google'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sing-Kai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <PageContainer>
        <PageItems>
        <PageItem>
          <h1>Title</h1>
        </PageItem>
        <PageItem>
          <p>Lose john poor same it case do year we. Full how way even the sigh. Extremely nor furniture fat questions now provision incommode preserved. Our side fail find like now. Discovered travelling for insensible partiality unpleasing impossible she. Sudden up my excuse to suffer ladies though or. Bachelor possible marianne directly confined relation as on he.

Speedily say has suitable disposal add boy. On forth doubt miles of child. Exercise joy man children rejoiced. Yet uncommonly his ten who diminution astonished. Demesne new manners savings staying had. Under folly balls death own point now men. Match way these she avoid see death. She whose drift their fat off.

Now led tedious shy lasting females off. Dashwood marianne in of entrance be on wondered possible building. Wondered sociable he carriage in speedily margaret. Up devonshire of he thoroughly insensible alteration. An mr settling occasion insisted distance ladyship so. Not attention say frankness intention out dashwoods now curiosity. Stronger ecstatic as no judgment daughter speedily thoughts. Worse downs nor might she court did nay forth these.

It if sometimes furnished unwilling as additions so. Blessing resolved peculiar fat graceful ham. Sussex on at really ladies in as elinor. Sir sex opinions age properly extended. Advice branch vanity or do thirty living. Dependent add middleton ask disposing admitting did sportsmen sportsman.

Nor hence hoped her after other known defer his. For county now sister engage had season better had waited. Occasional mrs interested far expression acceptance. Day either mrs talent pulled men rather regret admire but. Life ye sake it shed. Five lady he cold in meet up. Service get met adapted matters offence for. Principles man any insipidity age you simplicity understood. Do offering pleasure no ecstatic whatever on mr directly.
          </p>
        </PageItem>
        </PageItems>
      </PageContainer>
    </>
  )
}

const PageContainer = styled.div`
  justify-content: center;
  background: yellow;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  margin: auto;
  margin-top: 100px;
  width: 60%;
  position: relative;
`;

const PageItems = styled.div`
  margin: 50px 10px 50px 10px;
  position: relative;
  max-height: 100vh;

`;

const PageItem = styled.div`
  background:pink;
  margin: 5px;
  padding: 5px;
`;


