import Head from 'next/head'
import styled from 'styled-components';
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
// import Layout from '../src/components/Layout'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Sing-Kai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <PageContainer>
        <PageItem>
          <h1>Title</h1>
        </PageItem>
        <PageItem>
          <p>Profile Page Work In Progress</p>
        </PageItem>
      </PageContainer>
    </>
  )
}

const PageContainer = styled.div`
  justify-content: center;
  background: yellow;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  margin: 100px 100px 100px 100px;
  max-height: 100vh;
`;

const PageItem = styled.div`
  background:pink;
  margin: 5px;
  padding: 5px;
`;


